### ISSUE TITLE
Support for other Languages

### ISSUE THREAD

**Issue by Alex--C** [atfinke/WikiRaces#146]
Heya,

First of all: I absolutely love your game! Lots of fun to play with a group of friends.

One feature that I'm missing is support for other languages. Are you already planning that or would you be open for a PR? Not sure if I would be able to properly implement it, since my Swift/iOS skills are pretty much non-existent, but I could try it. From what I've seen, the article list and the Wikipedia URLs are hardcoded, but I guess that shouldn't be too hard to change. I could also offer help with translating the app itself to German.

Let me know your thoughts on this topic :-)

**Comment by atfinke** [comment]
Hi Alex!

Thanks for taking the time to write up this request and for your feedback!! Unfortunately, after working on WikiRaces for more than **six** years, I’ll soon have to stop all development due to legal agreements with my future employer. 

I think it would be great to add international support to the game, however, I don’t think there is time to implement it before I have to cease updating the app.

Ping me on Twitter (@_andrewfinke) and I’ll send you a code to unlock WikiRaces+.

Andrew

**Comment by atfinke** [comment]
Actually this might be easier than I thought… I’ll do some more investigating. Definitely still ping me on Twitter!

**Comment by atfinke** [comment]
Shipped initial support in 2020.08

**Comment by atfinke** [comment]
In summary: Added basic support for in-game language selection. Full localization of the app (menus, alerts, etc.) is out of scope due to time constraints.
